In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# Matrizes e Vetores Multidimensionais

## Matrizes e Vetores Multidimensionais em Python

-   Matrizes e Vetores Multidimensionais são generalizações de vetores simples vistos anteriormente.

-   Suponha por exemplo que devamos armazenar as notas de cada aluno em cada laboratório de MC102.

    Podemos alocar 15 vetores (um para cada lab) de tamanho 50 (tamanho da turma), onde cada vetor
  representa as notas de um laboratório específico.

    Matrizes e Vetores Multidimensionais permitem fazer a mesma coisa mas com todas as informações
  sendo acessadas por um nome em comum (ao invés de 15 nomes distintos).

### Criação de Matrizes

#### Declarando uma matriz com listas

-   Para criar uma matriz de dimensões $l \times c$ inicialmente vazia podemos utilizar uma *“list comprehension”*.

**Exemplo** de uma matriz $3 \times 4$ inicialmente zerada:

In [ ]:
# vamos criar uma matriz com 3 linhas vazias
mat = [[] for i in range(3)]
mat

In [ ]:
# vamos preencher cada linha com 4 zeros
mat = [[0 for j in range(4)] for i in range(3)]
mat

-   Lembre-se de que os indices de uma lista sempre começam em 0.
-   Note que cada lista interna representa uma linha da matriz

#### Exemplo de declaração de matriz

-   Criar uma matriz $3 \times 4$ onde cada posição $(i,j)$ contém o valor $i \cdot j$.

In [ ]:
# Usando laços for:

mat = []
for i in range(3):         # para cada linha i de 0 até 2
    l = []                 #    linha i começa vazia
    for j in range(4):     #    para cada coluna j de 0 até 3
        l.append(i * j)    #        preenche a coluna j da linha i
    mat.append(l)          #adiciona linha i à matriz
print(mat)

In [ ]:
# Usando list comprehension:

mat = [[i * j for j in range(4)] for i in range(3)]
print(mat)

### Acesso a elementos de uma matriz

-   Em qualquer lugar onde você usaria uma variável no seu programa, você pode usar um elemento específico de uma matriz da seguinte forma:   
    ```nome_da_matriz[ind_linha][ind_coluna]```   
    onde ```ind_linha```  e ```ind_coluna``` são inteiros especificando a linha e a coluna a serem acessadas.

-   No exemplo abaixo é criada uma matriz $4 \times 3$ inicializada com zeros, e depois
  é atribuído o valor 23 para o elemento na 2ª linha e 3ª coluna.

In [ ]:
# cria matriz 10x20 toda com zeros
mat = [[0 for j in range(4)] for i in range (3)]

# atribui o valor 23 ao elemento na 2a linha, 3a coluna
mat[1][2] = 23

print(mat)

-   Lembre-se de que, como a matriz está implementada com listas, a primeira posição de qualquer dimensão corresponde ao índice 0.   
    Por exemplo, ```mat[1][2]``` refere-se ao elemento na 2ª linha e 3ª coluna da matriz ```mat```.

In [ ]:
print(mat[1][2])

O acesso a posições inválidas causa um erro de execução.   
Por exemplo, ...

In [ ]:
mat[15][32]

### Declarando Vetores Multidimensionais

-   Podemos criar vetores multi-dimensionais utilizando listas de listas como no caso bidimensional.

-   Para criar um vetor de dimensões $d_1 \times d_2 \ldots \times d_l $ inicialmente vazio podemos 
    utilizar uma *“list comprehension”*:
    $$ [\, [ \,[ \,[\,]\, \text{for}\, i_{l-1} \, \text{in range}(d_{l-1}) \, ] \ldots \, ] \, 
    \text{for}\, i_2 \, \text{in range}(d_2)\,] \, \text{for} \, i_1 \, \text{ in range}(d_1)]
    $$

-   Exemplo de vetor $3 \times 4 \times 5$ inicialmente vazio

In [ ]:
mat = [ [ [] for j in range(4) ] for i in range(3) ]
mat

-   Exemplo de vetor $3 \times 4 \times 5$ inicialmente zerado.

In [ ]:
mat = [ [ [0 for k in range(5)] for j in range(4) ] for i in range(3) ]
mat

### Operando sobre vetores multidimensionais

Criar funções que executem operações básicas sobre matrizes quadradas:
-   Soma de 2 matrizes com dimensão $n \times n$.
-   Subtração de 2 matrizes com dimensão $n \times n$.
-   Cálculo da transposta de uma matriz de dimensão $n \times n$.
-   Multiplicação de 2 matrizes com dimensão $n \times n$.

#### Leitura de uma matriz n x n
Vamos implementar uma função que faça a leitura de uma matriz com dimensão $n \times n$:

In [ ]:
# Função que lê uma matriz n x n do teclado, linha por linha
def ler_matriz(n):
    mat = [[] for i in range(n)]
    for i in range(n):
        aux = input(f'Linha {i}: ').split()
        for j in range(n):
            mat[i].append(float(aux[j]))
    return mat

In [ ]:
n = int(input('Dimensão da matriz: '))
mat = ler_matriz(n)
mat

Ou, simplificando, com uma *“list comprehension”*...

In [ ]:
# Função que lê uma matriz n x n do teclado, linha por linha
def ler_matriz(n):
    return [[float(x) for x in input(f'Linha {i}: ').split()] for i in range(n)]

In [ ]:
n = int(input('Dimensão da matriz: '))
mat = ler_matriz(n)
mat

#### Impressão de uma matriz n x n
Vamos implementar uma função que faça a impressão de uma matriz com dimensão $n \times n$:

In [ ]:
# Função que exibe uma matriz n x n no terminal, linha por linha
def exibir_matriz(mat):
    for linha in mat:
        print(linha)

In [ ]:
exibir_matriz(mat)

#### Exemplo: Soma de Matrizes n x n

In [ ]:
def somar_matrizes(mat_a, mat_b):
    n = len(mat_a)
    mat_s = [[0 for j in range(n)] for i in range(n)]
    for i in range(n):
        for j in range(n):
            mat_s[i][j] = mat_a[i][j] + mat_b[i][j]
    return mat_s

#### Exemplo: Multiplicação de Matrizes

-   Vamos criar uma função que multiplique duas matrizes $ma$ e $mb$ (de dimensão $n \times n$) e retorne o  resultado em uma terceira matriz $mc$.
-   Lembre-se de que uma posição $(i,j)$ de $mc$ terá o produto interno do vetor linha $i$
de $ma$ pelo vetor coluna $j$ de $mb$:
$$ mc_{i\,j} = \sum_{k=0}^{n-1} ma_{i\,k} \cdot mb_{k\,j} $$

-   Na implementação, para cada posição $[i,j]$ de $mc$
devemos computar
$$ mc[i,j] = \sum_{k=0}^{n-1} ma[i,k] \cdot mb[k,j]$$
-   Assim, nossa função poderá ser...

In [ ]:
def multiplicar_matrizes(ma, mb):
    n = len(ma)
    mc = [[0 for j in range(n) ] for i in range(n)]
    for i in range(n):
        for j in range(n):
            for k in range(n): #calcula prod. interno da linha i por coluna j
                mc[i][j] += ma[i][k] * mb[k][j]
    return mc

In [ ]:
#n = int(input('Dimensão da matriz: '))
n = 3
# ma = ler_matriz(n)
ma = [[1, 2, 3], [0, 1, 4], [5, 6, 0]]

# mb = ler_matriz(n)
mb = [[-24, 18, 5], [20, -15, -4], [-5, 4, 1]]

mc = multiplicar_matrizes(ma, mb)

exibir_matriz(mc)

#### Exemplo: Cálculo da transposta de uma matriz n x n
-   Escrever uma função que calcule a transposta de uma matriz $n \times n$.   

-   A transposta de uma matriz $ma$ é uma matriz $mt$ tal que $mt_{i\,j} = ma_{j\,i}$ 
    para $0 \le i \lt n$ e $0 \le j \lt n$.

In [ ]:
def transposta(ma):
    n = len(ma)
    mt = [[0 for j in range(n)] for i in range(n)]
    for i in range(n):
        for j in range(n):
            mt[i][j] = ma[j][i]
    return mt

In [ ]:
ma = [[1, 2, 3], [0, 1, 4], [5, 6, 0]]
print(transposta(ma))

Ou usando uma *“list comprehension”*...

In [ ]:
ma = [[1, 2, 3], [0, 1, 4], [5, 6, 0]]
n = len(ma)

mt = [[linha[i] for linha in ma] for i in range(n)]
print(mt)

## Vetores multidimensionais homogêneos mais eficientes com NumPy

-   NumPy é um módulo para Python desenvolvido para tratar eficientemente vetores multidimensionais homogêneos.   
    Para que NumPy possa ser usado em um programa, é preciso importar o módulo ```numpy```.   
    Por exemplo...

In [13]:
import numpy as np

-   Um vetor multidimensional homogêneo é uma
tabela de elementos (geralmente números), todos do mesmo tipo, indexados por um
tupla de inteiros positivos.

-   Em NumPy, as dimensões são chamadas *eixos*.

-   Por exemplo, as coordenadas de um ponto no espaço 3D ```[1, 2, 1]``` representam 
um eixo.  
    Esse eixo tem 3 elementos e, por isso, dizemos que ele tem comprimento 3.

-   No exemplo abaixo, o vetor tem 2 eixos.   
    O primeiro eixo tem comprimento 2 e o segundo comprimento 3.   
    ```
    [[1., 0., 0.],   
     [0., 1., 2.]]
    ```

A classe de vetores de NumPy é chamada ```ndarray```.   
Ela também é conhecida pelo apelido ```array```.

Note que ```numpy.array``` não é a mesma coisa que a classe ```array.array``` da biblioteca padrão
de Python, que lida apenas com vetores unidimensionais e oferece menos funcionalidades.

Considere o objeto ```numpy.array``` abaixo

In [14]:
a = np.array([[1., 0., 0.], [0., 1., 2.]])
a

array([[1., 0., 0.],
       [0., 1., 2.]])

Os atributos mais importantes desse objeto são:

-   **ndarray.ndim**   
    É o número de eixos (dimensões) do vetor.

In [15]:
a.ndim

2

-   **ndarray.shape**   
    São as dimensões do vetor.   
    Esta é uma tupla de inteiros indicando
o tamanho do vetor em cada dimensão.   
Para um vetor com $n$ linhas e $m$ colunas, ```shape``` será $(n, m)$.   
O comprimento da tupla ```shape``` é, portanto, o número de eixos, ``` ndim```.

In [16]:
a.shape

(2, 3)

-   **ndarray.size**   
    É o número total de elementos no vetor.   
    Ele é igual ao produto dos elementos da tupla ```shape```.
  

In [17]:
a.size

6

-   **ndarray.dtype**   
    É um objeto que descreve o tipo dos elementos na matriz.   
    É possível criar ou especificar ```dtype```s usando tipos padrão do Python.   
    Além disso NumPy oferece tipos próprios, como ```numpy.int32```, ```numpy.int16``` e 
```numpy.float64```, por exemplo.

In [18]:
a.dtype

dtype('float64')

-   **ndarray.itemsize**   
    É o tamanho em bytes de cada elemento do vetor.   
    Por exemplo, um vetor de elementos do tipo ```float64``` tem ```itemsize``` 8 (= 64/8), enquanto um do tipo ```complex32``` tem ```itemsize``` 4 (= 32/8). 
    Ele é equivalente a ```ndarray.dtype.itemsize```.

In [19]:
a.itemsize

8

-   **ndarray.data**   
    É o bufferonde realmente estão os elementos do vetor.   
    Normalmente nós não precisaremos usar esse atributo porque acessaremos os elementos
de um vetor usando recursos de indexação.

In [20]:
a.data

## Criação de vetores

Existem várias maneiras de criar vetores em NumPy.

Por exemplo, você pode criar uma matriz a partir de uma lista ou tupla comum do Python usando a função ```array```.   
O tipo da matriz resultante é deduzido do tipo dos elementos nas sequências.

In [21]:
a = np.array([2, 3, 4])
a.dtype

dtype('int64')

In [22]:
b = np.array([1, 3, 5.1])
b.dtype

dtype('float64')

Um erro frequente consiste em chamar ```array``` com múltiplos argumentos numéricos, ao invés de fornecer uma única lista de números como **um** argumento.

In [23]:
a = np.array(1,2,3,4)    # WRONG

ValueError: only 2 non-keyword arguments accepted

In [24]:
a = np.array([1,2,3,4])  # RIGHT
a

array([1, 2, 3, 4])

```array``` transforma sequências de sequências em vetores bidimensionais, sequências de sequências de sequências em vetores tridimensionais e assim por diante.

In [26]:
b = np.array([(1.5,2,3), (4,5,6)])
b.dtype
b

dtype('float64')

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

O tipo do vetor também pode ser explicitamente especificado no momento da criação:

In [27]:
c = np.array([[1, 2], [3, 4]], dtype=complex)
c.dtype
c

dtype('complex128')

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

Muitas vezes não conhecemos os elementos de um vetor no momento da criação, apenas o tamanho do vetor é conhecido.   
Por isso, NumPy oferece várias funções para criar vetores apenas reservando espaço.   
Isso minimiza a necessidade de fazer vetores crescerem, que é uma operação cara.

A função ```zeros``` cria um ``` array``` cheio de zeros, a função ```ones``` cria um vetor cheio de uns e a função ```empty``` cria um vetor cujo conteúdo inicial é imprevisível pois depende do estado da memória.   
Por padrão, o ```dtype``` do vetor criado é ```float64```.

In [28]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [29]:
# dtype can also be specified
np.ones((2,3,4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [30]:
# uninitialized, output may vary
np.empty((2,3))

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

Para criar sequências de números, NumPy fornece uma função análoga a ```range``` que retorna vetores ao invés de listas.

In [31]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [35]:
# arange accepts float arguments
np.arange(0, 2, 0.25)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75])

Quando ```arange``` é usado com argumentos de ponto flutuante, geralmente não é possível prever o número de elementos obtidos, devido à precisão finita das operações de ponto flutuante.   

Por esta razão, normalmente é melhor usar a função ```linspace``` que recebe como argumento o número desejado de elementos, ao invés de um passo.   
É importante salientar que, ao contrário de ```arange```, ```linspace``` inclui os dois pontos extremos ```start``` e ```stop```.

In [37]:
from numpy import pi
# 9 números de 0 a 2
np.linspace( 0, 2, 9 )

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [47]:
# linspace é útil para avaliar funções em muitos pontos
x = np.linspace(0, 2*pi, 361)
f = np.sin(x)

np.set_printoptions(precision=3, suppress=True)
print(f[0:361:30])

[ 0.     0.5    0.866  1.     0.866  0.5    0.    -0.5   -0.866 -1.
 -0.866 -0.5   -0.   ]


## Manipulação da Forma

### Mudando a forma de um vetor
A forma de um vetor é dada pelo número de elementos ao longo de cada eixo:

In [50]:
a = np.floor(10 * np.random.random((3,4)))
a

array([[2., 3., 9., 4.],
       [6., 1., 1., 2.],
       [4., 6., 0., 3.]])

In [ ]:
a.shape

A forma de um vetor pode ser alterada por vários comandos.   
Note que os três comandos a seguir retornam uma matriz modificada, mas não alteram a matriz original:

In [ ]:
a.ravel()  # retorna o vetor, achatado

In [ ]:
a.reshape(2, 6)  # retorna o vetor, com uma nova forma

In [ ]:
a.T  # retorna a transposta do vetor

In [ ]:
a.T.shape

In [ ]:
a.shape

A ordem dos elementos no vetor resultante de ```ravel()``` é normalmente “estilo-C”, isto é, o índice mais à direita “muda mais rápido”.   
Assim, o elemento que vem depois de ```a [0,0]``` é ```a [0,1]```.

Quando um vetor é reformatado, ele também é tratado em “estilo-C”.

Como NumPy normalmente armazena seus vetores nessa ordem, ```ravel()``` normalmente não precisará copiar seu argumento.   
No entanto, se o vetor foi criado a partir de fatias de outro vetor ou de opções incomuns, a cópia pode ser necessária.

As funções ```ravel()``` e ```reshape()``` também podem ser chamadas incluindo-se um argumento opcional, para usar “estilo-FORTRAN”, no qual o índice mais à esquerda muda mais rapidamente.

A função ```reshape``` retorna seu argumento com uma forma modificada, enquanto o método```nda.resize``` modifica o próprio array ```nda```:

In [ ]:
a
a.resize((2,6))
a

Se uma dimensão for dada como -1 em uma operação de redimensionamento, as outras dimensões são calculadas automaticamente:

In [ ]:
a.reshape(4, -1)

## Impressão de vetores
Quando você imprime um vetor, NumPy o exibe de maneira semelhante a listas aninhadas, mas com o seguinte layout:

-   o último eixo é impresso da esquerda para a direita,
-   o penúltimo eixo é impresso de cima para baixo,
-   o resto do vetor também é impresso de cima para baixo, com cada fatia separada da próxima por uma linha em branco.

Assim, vetores unidimensionais são impressos como linhas, vetores bidimensionais como matrizes e vetores tridimensionais como listas de matrizes.

In [ ]:
# vetor unidimensional
a = np.arange(6)
print(a)

In [ ]:
# vetor bidimensional
b = np.arange(12).reshape(4,3)
print(b)

In [ ]:
# vetor tridimensional
c = np.arange(24).reshape(2,3,4)
print(c)

In [ ]:
# vetor quadridimensional
d = np.arange(48).reshape(2,3,2,4)
print(d)

Quando um vetor é muito grande para ser impresso, NumPy omite automaticamente a parte central do vetor e exibe apenas as pontas:

In [ ]:
print(np.arange(10000))

In [ ]:
print(np.arange(10000).reshape(100,100))

Para desabilitar esse comportamento e forçar NumPy a imprimir todo o vetor, você pode alterar as opções de impressão usando ```set_printoptions```.

## Operações básicas
Os operadores ```*, - , + , /``` e ```**```, quando aplicados sobre vetores, atuam elemento a elemento.   
Um novo vetor é criado e preenchido com o resultado.

In [ ]:
m = np.ones((2,3))
m + 1

In [ ]:
m * 4

In [ ]:
m = m + 1
m

In [ ]:
m ** 3

In [ ]:
a = np.array([20,30,40,50])
a

In [ ]:
b = np.arange(4)
b

In [ ]:
c = a - b
c

In [ ]:
b ** 2

In [ ]:
10 * np.sin(a)

In [ ]:
a < 35

Ao contrário de muitas linguagens para matrizes, em NumPy o operador de produto ```*``` é aplicado elemento a elemento.   
O produto de vetores pode ser feito usando a função ou método ```dot```:

In [ ]:
ma = np.array( [[1,1],
               [0,1]] )
mb = np.array( [[2,0],
               [3,4]] )

# produto elemento a elemento
ma * mb

In [ ]:
# produto de matrizes
ma.dot(mb)

In [ ]:
# outro produto de matrizes
np.dot(ma, mb)

Algumas operações, como ```+=``` e ```*=```, atuam diretamente modificando uma matriz existente, em vez de criar uma nova.

In [ ]:
a = np.ones((2,3), dtype=int)
a *= 3
a

In [ ]:
b = (np.random.randint(1, 10 + 1, 6) / 10).reshape(2, 3)
b

In [ ]:
# a é automaticamente convertida para float
b += a
b

In [ ]:
# b não é automaticamente convertida para int 
a += b

Ao operar com vetores de tipos diferentes, o tipo do vetor resultante corresponde ao tipo mais geral ou mais preciso (um comportamento conhecido como *upcasting*).

In [ ]:
a = np.ones(3, dtype=np.int32)
a.dtype.name
a

In [ ]:
b = np.linspace(0, np.pi, 3)
b.dtype.name
b

In [ ]:
c = a + b
c.dtype.name
c

In [ ]:
d = np.exp(c * 1j)
d.dtype.name
d

Muitas operações unárias, como calcular a soma de todos os elementos na matriz, são implementadas como métodos da classe ```ndarray```.

In [ ]:
a = np.random.randint(1, 10, (2,3))
a

In [ ]:
a.sum()

In [ ]:
a.min()

In [ ]:
a.max()

Por padrão, essas operações se aplicam ao vetor como se ele fosse uma lista de números, independentemente de sua forma.   
No entanto, se especificarmos o parâmetro ```axis``` você pode aplicar uma operação ao longo de um eixo especificado de um vetor:

In [ ]:
a.min(axis=0)   # menores valores ao longo do eixo 0

In [ ]:
a.max(axis=1)   # maiores valores ao longo do eixo 1

In [ ]:
b = np.arange(12).reshape(3,4)
b

In [ ]:
# soma de cada coluna
b.sum(axis=0)

In [ ]:
# mínimo de cada linha
b.min(axis=1)

In [ ]:
# soma cumulativa ao longo de cada linha
b.cumsum(axis=1)

In [ ]:
# comment out the next line to change the printing options
# np.set_printoptions(threshold=np.nan)

### Operações de álgebra linear

NumPy oferece diversas operações de algebra linear no pacote ```numpy.linalg```.

#### Produto de matrizes
O produto de duas matrizes $ma$ e $mb$ é calculado por $\textrm{numpy.dot}(ma, mb)$.

In [ ]:
a = np.arange(9).reshape(3,3)
a

In [ ]:
b = 2 * np.ones((3, 3))
b

In [ ]:
np.dot(a, b)

In [ ]:
np.dot(b,a)

### Inversão de matrizes
A inversa de uma matriz $ma$ é calculada por $\textrm{numpy.linalg.inv}(ma)$.

In [ ]:
a = np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]])
a

In [ ]:
b = np.linalg.inv(a)
b

In [ ]:
np.dot(a,b)

### Solução de sistemas de equações
Um sistema de equações lineares dado por uma matriz de coeficientes $mc$ e um vetor de termos constantes $tc$ pode ser resolvido por $\textrm{numpy.linalg.solve}(mc, tc)$.

Por exemplo, vamos resolver o seguinte sistema:
$$
\left\{
\begin{array}{r r r c r}
 3x_0 & +4x_1 & +  x_2 & = & 14  \\
  x_0 & - x_1 & + 2x_2 & = &  5  \\
-2x_0 & +3x_1 & -  x_2 & = &  1
\end{array}
\right.
$$

In [ ]:
mc = np.array([[3., 4., 1.],
               [1., -1., 2.],
               [-2., 3., -1.]])
tc = np.array([14., 5., 1.])

In [ ]:
x = np.linalg.solve(mc, tc)
print(x)